version: '3.8'

services:

  api:
    build: https://github.com/yututi/mtg-api.git
    environment:
      - LOG_LEVEL=debug
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
      - ENABLE_RESPONSE_VALIDATION=yes
      - FRONTEND_HOST=*
      - PORT=3000
    ports:
      - 3000:3000
    depends_on: 
      - db

  batch:
    build: https://github.com/yututi/mtg-data-import-ja.git#main
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
      - JSON_URL=https://mtgjson.com/api/v5/Pioneer.json
      - KEEP_JSON_FILE=yes
      - LOG_LEVEL=debug
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    tty: true
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

