import Head from 'next/head'
import Slider from '@/components/Slider'
import { CachedPageProvider } from '@/state/CachedPageContext'
import { PaginationProvider } from '@/state/PaginationContext'
import ControlPanel from '@/components/search/ControlPanel'
import Container from "@/components/Container"
import { DeckListProvider } from '@/state/DeckListContext'
import { SWRConfig } from 'swr'
import CardDetailDialog from '@/components/CardDetailDialog'


export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <SWRConfig value={{
          revalidateIfStale: false,
          revalidateOnFocus: false,
          revalidateOnReconnect: false
        }}>
          <Container>
            <DeckListProvider>
              <ControlPanel />
              <PaginationProvider>
                <CachedPageProvider>
                  <Slider />
                </CachedPageProvider>
              </PaginationProvider>
            </DeckListProvider>
          </Container>
          <CardDetailDialog />
        </SWRConfig>
      </main>
    </>
  )
}
