import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { CardApi } from '../lib/gen/axios'
import useCardList from '../hooks/useCardList'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [page, setPage] = useState(0)

  const result = useCardList({
    page,
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          {!result.isLoading && result.data?.data.list?.map(data => (<div key={data.uuid}>{data.name}</div>))}
        </div>
      </main>
    </>
  )
}
